# Generated by Django 4.2 on 2023-04-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamer_id', models.PositiveIntegerField()),
                ('gamer_username', models.CharField(max_length=50)),
                ('game_first_name', models.CharField(max_length=50)),
                ('game_last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('gamer_games', models.CharField(max_length=100)),
            ],
        ),
    ]
