# Generated by Django 4.2 on 2023-04-14 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamer',
            old_name='game_first_name',
            new_name='gamer_first_name',
        ),
        migrations.RenameField(
            model_name='gamer',
            old_name='game_last_name',
            new_name='gamer_last_name',
        ),
    ]
