# Generated by Django 4.1.7 on 2023-05-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_rename_game_first_name_gamer_gamer_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_names', models.CharField(max_length=100)),
                ('game_images', models.ImageField(help_text='.jpg,.png ,.jpeg, .gif, .svg supported', upload_to='thumbnail/', verbose_name='Game Thumbnails')),
                ('game_videos', models.FileField(help_text='.mp4 spported only', upload_to='videos/', verbose_name='Video')),
            ],
        ),
    ]
