# Generated by Django 4.1.7 on 2023-05-11 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_alter_games_game_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Games',
        ),
    ]
