# Generated by Django 4.1.7 on 2023-05-18 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_games'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamer',
            name='gamer_id',
        ),
    ]
